

###

POST http://localhost:3000/campeonato
Content-Type: application/json

{ 
"mandante": "3",
"golmandante": "4",
"visitante": "2",
"golvisitante": "4" 
 }


###
GET http://localhost:3000/campeonato

###
GET http://localhost:3000/classificacao